bugfix

diff --git a/config/helpers/lfs-libtool-archive-fixup b/config/helpers/lfs-libtool-archive-fixup
--- a/config/helpers/lfs-libtool-archive-fixup
+++ b/config/helpers/lfs-libtool-archive-fixup
@@ -1,6 +1,46 @@
-
 #!/bin/bash -
 set +o allexport -o braceexpand +o emacs -o errexit +o errtrace +o functrace +o hashall +o histexpand +o history +o ignoreeof -o interactive-comments +o keyword +o monitor +o noclobber +o noexec +o noglob +o nolog +o notify +o nounset +o onecmd +o physical +o pipefail +o posix +o verbose +o vi +o xtrace;unset BASH_ENV;unset BASH_XTRACEFD;unset CDPATH;unset ENV;unset FCEDIT;unset FIGNORE;unset FUNCNEST;unset GLOBIGNORE;unset HISTCONTROL;unset HISTFILE;unset HISTFILESIZE;unset HISTIGNORE;unset HISTSIZE;unset HISTTIMEFORMAT;unset HOSTFILE;unset IGNOREEOF;unset INPUTRC;unset MAIL;unset MAILCHECK;unset MAILPATH;unset TMOUT;umask 022
+
+function setDebugging()
+{
+	# is set -x on?
+	if [[ "$-" == *x* ]]; then
+		export LFS_BASH_DEBUGGING="yes"
+	elif [ ! -z "$LFS_BASH_DEBUGGING" ]; then
+		if [ "$LFS_BASH_DEBUGGING" = "yes" ]; then
+			set -x
+		fi
+	fi
+}
+
+function findOurNameAndPath()
+{
+	readonly ourName="$(basename "$0")"
+	pushd "$(dirname "$0")" >/dev/null
+	readonly crudeOurPath="$(pwd)"
+	popd >/dev/null
+}
+
+function exitError()
+{
+	local -r error="$1"
+	echo "$ourName: $error" 1>&2
+	exit 1
+}
+
+function exitHelp()
+{
+	echo -n -E "Usage: ${ourName} -h
+Usage: ${ourName} [-c lfsConfigPath] machine
+
+Defaults
+    lfsConfigPath      ${lfsConfigPath}
+
+A machine defines machine settings in <lfsConfigPath>/settings/machine/<machine>.settings
+
+" 1>&2
+	exit $1
+}
 
 function outputCommentAndVariables()
 {
@@ -69,20 +109,17 @@ function replaceLibDirWithPrefix()
 function processLibtoolArchive()
 {
 	if [ ! -f "$libtoolArchiveFile" ]; then
-		echo "Can not use $libtoolArchiveFile as it does not exist as a file" 1>&2
-		exit 1
+		exitError "Can not use $libtoolArchiveFile as it does not exist as a file"
 	fi
 		
 	local -r libtoolArchiveFileOrig="$libtoolArchiveFile".orig
 	if [ -e "$libtoolArchiveFileOrig" ]; then
-		echo "Can not create $libtoolArchiveFileOrig as it already exists" 1>&2
-		exit 1
+		exitError "Can not create $libtoolArchiveFileOrig as it already exists"
 	fi
 
 	local -r libtoolArchiveFileNew="$libtoolArchiveFile".new
 	if [ -e "$libtoolArchiveFileNew" ]; then
-		echo "Can not create $libtoolArchiveFileNew as it already exists" 1>&2
-		exit 1
+		exitError "Can not create $libtoolArchiveFileNew as it already exists"
 	fi
 	
 	local -r libtoolArchiveFileName="$(basename "$libtoolArchiveFile")"
@@ -101,6 +138,13 @@ function processLibtoolArchive()
 
 function main()
 {
+	setDebugging
+	findOurNameAndPath
+	
+	if [ $# -le 2 ]; then
+		exitError "Not enough arguments, needs at least LFS and rootPath"
+	fi
+	
 	readonly LFS="$1"
 	readonly rootPath="$2"
 	shift 2
