bugfix

diff --git a/lfs-next-uid b/lfs-next-uid
--- a/lfs-next-uid
+++ b/lfs-next-uid
@@ -1,6 +1,21 @@
 #!/bin/bash -
 set +o allexport -o braceexpand +o emacs -o errexit +o errtrace +o functrace +o hashall +o histexpand +o history +o ignoreeof -o interactive-comments +o keyword +o monitor +o noclobber +o noexec +o noglob +o nolog +o notify +o nounset +o onecmd +o physical +o pipefail +o posix +o verbose +o vi +o xtrace;unset BASH_ENV;unset BASH_XTRACEFD;unset CDPATH;unset ENV;unset FCEDIT;unset FIGNORE;unset FUNCNEST;unset GLOBIGNORE;unset HISTCONTROL;unset HISTFILE;unset HISTFILESIZE;unset HISTIGNORE;unset HISTSIZE;unset HISTTIMEFORMAT;unset HOSTFILE;unset IGNOREEOF;unset INPUTRC;unset MAIL;unset MAILCHECK;unset MAILPATH;unset TMOUT;umask 022
 
+function essentialProgramCheck()
+{
+	# This nasty hack exists because source'd files override the set -xxxx options!
+	set -e
+	
+	local program
+	for program in "$@"
+	do
+		if ! which "$program" 1>/dev/null 2>/dev/null; then
+			echo "$ourName: FAIL: Program $program does not exist on path $PATH" 1>&2
+			return 100
+		fi
+	done
+}
+
 function setDebugging()
 {
 	# is set -x on?
@@ -80,6 +95,18 @@ function parseCommandLine()
 	fi
 }
 
+function setLfsConfigPath()
+{
+	essentialProgramCheck mkdir awk
+	
+	if [ ! -d "$lfsConfigPath" ]; then
+		exitError "Config path $lfsConfigPath does not exist or is not a directory"
+	fi
+	pushd "$lfsConfigPath">/dev/null
+	lfsConfigPath="$(pwd)"
+	popd >/dev/null
+}
+
 function sourceFunctions()
 {
 	readonly functionsPath="$lfsConfigPath"/functions
@@ -95,16 +122,6 @@ function sourceFunctions()
 			source "$fileToSource"
 		done
 		
-	popd >/dev/null
-}
-
-function setLfsConfigPath()
-{
-	if [ ! -d "$lfsConfigPath" ]; then
-		exitError "Config path $lfsConfigPath does not exist or is not a directory"
-	fi
-	pushd "$lfsConfigPath">/dev/null
-	lfsConfigPath="$(pwd)"
 	popd >/dev/null
 }
 
